const samples={
  amore:[['Amare non significa guardarsi negli occhi, ma guardare insieme nella stessa direzione.','Antoine de Saint-Exupéry'],['L’amore è la poesia dei sensi.','Honoré de Balzac']],
  vita:[['La vita è ciò che accade mentre siamo impegnati a fare altri progetti.','John Lennon'],['La vita non è trovare se stessi. La vita è creare se stessi.','George Bernard Shaw']],
  motivazione:[['Il successo è la somma di piccoli sforzi, ripetuti giorno dopo giorno.','Robert Collier'],['Non aspettare. Il momento giusto non arriverà mai.','Napoleon Hill']],
  disciplina:[['La disciplina è il ponte tra gli obiettivi e i risultati.','Jim Rohn'],['Non devi essere estremo, devi essere costante.','Anonimo']]
};
const fallback=[['Ogni giorno è una nuova possibilità di diventare la persona che vuoi essere.','Dimmelo con una citazione']];
const key='dimmeloconunacitazione_history_v1';
function getHistory(){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}}
function saveHistory(x){localStorage.setItem(key,JSON.stringify(x));renderHistory()}
function pick(){const topic=document.querySelector('#topic').value.trim().toLowerCase();const list=samples[topic]||fallback;const used=new Set(getHistory().map(x=>x.quote));const available=list.filter(x=>!used.has(x[0]));return (available[0]||list[Math.floor(Math.random()*list.length)])}
function showPost(post){document.querySelector('#quoteText').textContent=post.quote;document.querySelector('#author').textContent='— '+post.author;document.querySelector('#caption').value=post.caption;document.querySelector('#hashtags').value=Array.isArray(post.hashtags)?post.hashtags.join(' '):post.hashtags||'';document.querySelector('#status').textContent=post.generated_at?'✓ Ultimo post AI caricato da GitHub.':'Anteprima pronta.'}
async function loadAI(){try{const r=await fetch('data/latest.json?'+Date.now());if(!r.ok)throw new Error();const post=await r.json();if(post.quote&&post.generated_at)showPost(post)}catch(e){}}
function setQuote(){const [q,a]=pick();showPost({quote:q,author:a,caption:`A volte una frase arriva nel momento giusto. 🤍\n\nTema: ${document.querySelector('#topic').value.trim()||'ispirazione'}.\n\nSalvala se vuoi ritrovarla più avanti.`,hashtags:[`#citazioni`,`#aforismi`,`#frasi`,`#${(document.querySelector('#topic').value.trim()||'ispirazione').replace(/\s+/g,'')}`,`#ispirazione`]});document.querySelector('#status').textContent='Anteprima locale generata. L’AI viene eseguita in modo sicuro da GitHub.'}
function renderHistory(){const h=getHistory();document.querySelector('#count').textContent=`${h.length} salvate`;const box=document.querySelector('#historyList');if(!h.length){box.innerHTML='<p class="empty">Le citazioni approvate appariranno qui.</p>';return}box.innerHTML=h.slice().reverse().map(x=>`<div class="history-item"><div>${escapeHtml(x.quote)}<br><small>— ${escapeHtml(x.author)}</small></div><small>${x.date}</small></div>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]))}
document.querySelector('#generate').onclick=loadAI;document.querySelector('#regenerate').onclick=loadAI;document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelector('#topic').value=b.textContent.toLowerCase();loadAI()});document.querySelector('#approve').onclick=()=>{const h=getHistory();h.push({quote:document.querySelector('#quoteText').textContent,author:document.querySelector('#author').textContent.replace(/^—\s*/,''),caption:document.querySelector('#caption').value,hashtags:document.querySelector('#hashtags').value,date:new Date().toLocaleString('it-IT')});saveHistory(h);document.querySelector('#status').textContent='✓ Approvato e salvato. Pubblicazione Instagram: prossima fase.'};renderHistory();loadAI();
