const samples={
  amore:[['Amare non significa guardarsi negli occhi, ma guardare insieme nella stessa direzione.','Antoine de Saint-Exupéry'],['L’amore è la poesia dei sensi.','Honoré de Balzac']],
  vita:[['La vita è ciò che accade mentre siamo impegnati a fare altri progetti.','John Lennon'],['La vita non è trovare se stessi. La vita è creare se stessi.','George Bernard Shaw']],
  motivazione:[['Il successo è la somma di piccoli sforzi, ripetuti giorno dopo giorno.','Robert Collier'],['Non aspettare. Il momento giusto non arriverà mai.','Napoleon Hill']],
  disciplina:[['La disciplina è il ponte tra gli obiettivi e i risultati.','Jim Rohn'],['Non devi essere estremo, devi essere costante.','Anonimo']]
};
const fallback=[['Ogni giorno è una nuova possibilità di diventare la persona che vuoi essere.','Dimmelo con una citazione']];
const key='dimmeloconunacitazione_history_v1';
function getHistory(){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}}
function saveHistory(x){localStorage.setItem(key,JSON.stringify(x));renderHistory()}
function pick(){const topic=document.querySelector('#topic').value.trim().toLowerCase();const list=samples[topic]||fallback;const used=new Set(getHistory().map(x=>x.quote));const available=list.filter(x=>!used.has(x[0]));return (available[0]||list[Math.floor(Math.random()*list.length)])}
function setQuote(){const [q,a]=pick();document.querySelector('#quoteText').textContent=q;document.querySelector('#author').textContent='— '+a;const topic=document.querySelector('#topic').value.trim()||'ispirazione';document.querySelector('#caption').value=`A volte una frase arriva nel momento giusto. 🤍\n\nTema: ${topic}.\n\nSalvala se vuoi ritrovarla più avanti.`;document.querySelector('#hashtags').value=`#citazioni #aforismi #frasi #${topic.replace(/\s+/g,'')} #ispirazione`;document.querySelector('#status').textContent='Anteprima generata. Nella prossima versione collegheremo l’AI.'}
function renderHistory(){const h=getHistory();document.querySelector('#count').textContent=`${h.length} salvate`;const box=document.querySelector('#historyList');if(!h.length){box.innerHTML='<p class="empty">Le citazioni approvate appariranno qui.</p>';return}box.innerHTML=h.slice().reverse().map(x=>`<div class="history-item"><div>${escapeHtml(x.quote)}<br><small>— ${escapeHtml(x.author)}</small></div><small>${x.date}</small></div>`).join('')}
function escapeHtml(s){return s.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]))}
document.querySelector('#generate').onclick=setQuote;document.querySelector('#regenerate').onclick=setQuote;document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelector('#topic').value=b.textContent.toLowerCase();setQuote()});document.querySelector('#approve').onclick=()=>{const h=getHistory();h.push({quote:document.querySelector('#quoteText').textContent,author:document.querySelector('#author').textContent.replace(/^—\s*/,''),caption:document.querySelector('#caption').value,hashtags:document.querySelector('#hashtags').value,date:new Date().toLocaleString('it-IT')});saveHistory(h);document.querySelector('#status').textContent='✓ Approvato e salvato. Pubblicazione Instagram: prossima fase.'};renderHistory();
